-- require('pluginconf.colorbuddy')
-- require('pluginconf.neosolarized')
-- require('pluginconf.gruvbox')
require('pluginconf.gruvbox-material')
require('pluginconf.lsp-config')
require('pluginconf.lspkind')
require('pluginconf.cmp')
require('pluginconf.lualine')
require('pluginconf.treesitter')
require('pluginconf.autopairs')
require('pluginconf.ts-autotag')
require('pluginconf.telescope')
require('pluginconf.webicons')
require('pluginconf.null-ls')
require('pluginconf.mason')

